---
- src: git@github.com:xussof/software_git
  scm: git
  version: master
  name: xussof.software_git

- src: git@github.com:xussof/common_set-vars-all
  scm: git
  version: master
  name: xussof.common_set-vars-all
